# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
owner: "D4 Software"
title: "The Process"
email: support@d4software.co.uk
description: > # this means to ignore newlines until "baseurl:"
  How we build software at D4: our whole project lifecycle, open-sourced.
baseurl: "/the-process" # the subpath of your site, e.g. /blog
production_url: "https://d4software.github.io" # the base hostname & protocol for your site
base_path: "https://d4software.github.io" # the base hostname & protocol for your site
twitter_username: d4software
github_username:  d4software

# Build settings
markdown: kramdown
